### PR TITLE
Add OVH in traefik settings

### PR DESCRIPTION
**Pull request by as-de-pique**
Working over here with :
- OVH registred domain name
- Hetzner dedi on Ubuntu 18.04 and latest PlexGuide

Every subdomains seems to work fine, those created before the commit AND those created after.

See the wiki on the fork in order to get the ovh API keys

Please don't ask me for support as I barely understood what I did (yep, noob here...)

### CODE REVIEW

**Comment by Admin9705** [comment]
it looks good, did it work for you?

**Comment by Admin9705** [comment]
update to edge if you want to see in the pg program.  thanks for the push!

**Comment by as-de-pique** [comment]
It does!

I didn’t even know about traefik before, it’s amazingly fast!! Subdomains works instantly with OVH api key when creating a container with PG, even those created prior to my commit worked right away on my setup.

OVH docs is so poor regarding their API it took me like 3 hours of googling just to find the right api key request page...

Feel free to copy/paste the wiki to your website, it might save you some headache from people asking how to get the keys : https://github.com/as-de-pique/PlexGuide.com-The-Awesome-Plex-Server/wiki/How-To---DNS-records-and-OVH-API-keys

BTW : thanks a million for such an amazing piece of code! I’ll eventually manage to watch something from my setup haha

**Comment by Admin9705** [comment]
hey will do, this will for instructions!  thanks again!  ya this code is jargoned; i learned alot more since.

**Pull request merged**
