### PR TITLE
Update rclone-en.sh

### PR DESCRIPTION
**Pull request by Deiteq**
just some text edits

### CODE REVIEW

**Comment by Deiteq** [comment]
@Admin9705,  Not sure how to automatically merge this, haven't seen any options to do so.

**Comment by Admin9705** [comment]
no problem, i'll check it shortly.

**Comment by Admin9705** [comment]
@Deiteq, ok going through it now. btw, the stuff works. remember that dockerfix from way back? had to implement that.  everytime plex booted up, plexdrive was gone.  well, i think you came after

**Comment by Admin9705** [comment]
looks good!

**Comment by Admin9705** [comment]
looks good

**Pull request merged**
