### PR TITLE
Monitoring Dashboard and Database

### PR DESCRIPTION
**Pull request by cmacnichol**
This adds an option to Install Netdata-Advanced in the support menu.  It will Install Prometheus, cAdvisor, Netdata and Grafana.  They will be pre-configured for use.

ToDo:
Default dashboards for Grafanas still need some work
IP Information Screen to display access ports can't handle multiple app installs at the same time
Need to tighten up how the network is used as some of this does not really need to be exposed publicly.

### CODE REVIEW

**Comment by cmacnichol** [comment]
Well, I solved the conflicts.  Then realized I could not actually save the changes...

**Comment by flicker-rate** [comment]
@Admin9705 Could you help resolve the code conflicts in the menu scripts? I'm not quite sure what's going on there, or what changed in the menu.

**Comment by cmacnichol** [comment]
@flicker-rate @Admin9705 
Missed your messages earlier.  Still on Discord?  Link is expired.  As for the changes to the menus, I figured out how to resolve the conflicts.  Just did not have rights to save them.

**Comment by flicker-rate** [comment]
@cmacnichol Try this link? https://discord.gg/GkrvWrA

**Pull request merged**
