### PR TITLE
Add SSL security headers, tell search robots go away

### PR DESCRIPTION
**Pull request by robertbaker**
Add SSL headers for better security, tell search robots go away. Upgrades to http2 if it can.

### CODE REVIEW

**Comment by Admin9705** [comment]
this is awesome, will check into it

**Comment by YipYup** [comment]
@Admin9705 - You should make the HSTS an opt-in option and **not turned on by default**. There are massive issues that are possible if it propagates and the server admin makes changes later on.

Read: https://hstspreload.org/#opt-in

**Comment by robertbaker** [comment]
@YipYup That's only an issue if there's a subdomain that is only reachable by http, which would be a stupid thing to have these days, especially for our purposes....

**Comment by Admin9705** [comment]
ok testing out

**Comment by Admin9705** [comment]
had to undo the changes, forced me rebuild my test box :D

**Comment by robertbaker** [comment]
That's odd, any idea on the issue?

**Pull request merged**
