### PR TITLE
Allow path separators in download path (eg. /mnt/sdb/plexguide)

### PR DESCRIPTION
**Pull request by zotanw**
(this time to correct branch)

### CODE REVIEW

**Comment by Admin9705** [comment]
oh nice, will check it out!

**Comment by Admin9705** [comment]
looks good. i'm busy with several things, but will test this out.  good catch on the /mnt move piece

**Comment by zotanw** [comment]
Added another fix regarding the same problem

**Comment by zotanw** [comment]
I think that should be all now

**Comment by zotanw** [comment]
just tested, should be working now

**Comment by Admin9705** [comment]
no your fine :D pushing to 7.7 edge; starting 15 jan, the correct version of the edge to push to will be on the front

**Comment by Admin9705** [comment]
ok adding, thanks truly for your help with this :D

**Comment by zotanw** [comment]
no problem :)

**Pull request merged**
