### PR TITLE
fix qbitorrent and lazylibrarian

### PR DESCRIPTION
**Pull request by robertbaker**
fixes a few qbittorrent bugs.

### CODE REVIEW

**Comment by Admin9705** [comment]
looks good, the only problem i see here is with sonarr and i think radarr. for example, my path is unionfs/zilch/tv; this would basically prevent my server from working; as your has unionfs/tv it the reason why i leave unionfs open ended

**Comment by robertbaker** [comment]
Oh I see, I'll revert those lines.

**Comment by Admin9705** [comment]
ya we have to be careful with certain things; it's why some things are open ended :D haha my plex would have dropped everything :D

**Comment by robertbaker** [comment]
@Admin9705 reverted, please review

**Comment by Admin9705** [comment]
will do @robertbaker your the man :D

**Comment by Admin9705** [comment]
looks great!

**Pull request merged**
