### PR TITLE
Math fix.

### PR DESCRIPTION
**Pull request by YipYup**
Fix bug in count.

### CODE REVIEW

**Comment by Admin9705** [comment]
@flicker-rate

**Comment by YipYup** [comment]
I just switched it in the pull request with a simpler method that does it in one line rather than two. Just uses grep instead of  " cat + wc -l > +1 ". I realized the first way I submitted could still be prone to error as someone could manually edit the file and add in tons of line breaks, so this new way doesn't count line breaks at all, it counts the number of occurrences of the @ symbol which can only exist once per username.

**Comment by Admin9705** [comment]
@YipYup sounds good, @flicker-rate can u check when u have a chance :D it's we held off incase 🗡

**Comment by Admin9705** [comment]
No response accepted

**Pull request merged**
