### PR TITLE
Updated NZBGet Config File

### PR DESCRIPTION
**Pull request by cmacnichol**
Updated NZBGet Conf for Lidarr Copatability and corrected regex mappings

### CODE REVIEW

**Comment by Admin9705** [comment]
@cmacnichol this looks good, but did you test it?  NZBGET's file is weird.  I did the same thing; 1... 2... 3... and 4.  Sounds logical, but if you do this; it doesn't work.

**Comment by Admin9705** [comment]
i will look into this request regarding the music.  when it deploys, it does deploy like this by default.

https://ibb.co/fOGD97
https://ibb.co/mPJFNS

Closing to prevent confusion, but will look into the music part this weekend to fix. might just fix lidarr to deploy correctly instead

**Comment by cmacnichol** [comment]
Odd.  It worked on my system when I tested it.   I will try it on a new Ubuntu install layer tonight. Even tested the regex in a regex tester....

**Comment by Admin9705** [comment]
no it's fine, just gotta study it, reopen, then add :D

**Pull request closed without merging**
