### PR TITLE
fix: qbittorrent and sab having the same ext port, which is not allowed.

### PR DESCRIPTION
**Pull request by robertbaker**

### CODE REVIEW

**Comment by Admin9705** [comment]
the problem with this is qbit doesn't work if switched; it's a problem that i was gonna start solving soon. going to write up wikis and go through all the apps and iron out mini solutions

**Comment by robertbaker** [comment]
What do you mean it doesn't work? It works fine.

**Comment by Admin9705** [comment]
everytime i deploy it with the changed port, it times out on my end. i don't use the program, but last time it was changed, 3 others hit me up lol :D

**Comment by robertbaker** [comment]
Oh that's because in sab/get the port for qbit needs updated. You can't
have qbit and sab installed at the same time because they both map to 8080
on the machine. I've been using qbit and sab with sonarr radarr and LL just
fine with qbit mapped to 8081.

Trust me on this.

**Comment by robertbaker** [comment]
You don't need to change the port on those clients if they are on the
same.machine and you use local hostname to connect "qbittorrent" 8080
through sonarr/radarr works fine with this PR.

What timeout?

**Comment by danjames92** [comment]
@robertbaker Here's a project worth spending your time on.

https://github.com/Cloudbox/Cloudbox

**Comment by Admin9705** [comment]
i'll fix this on the rewrite for traefik.

**Pull request closed without merging**
