### PR TITLE
add flood

### PR DESCRIPTION
**Pull request by robertbaker**
Adds linuxserver/flood

I've tested this and it works.

### CODE REVIEW

**Comment by Admin9705** [comment]
i'll add these in, just doing some works on the drives before :D

**Comment by luxus** [comment]
why you closed the PR?

**Comment by luxus** [comment]
Thanks for your long answer.
Imho should we have a rtorrent rutorrent and a flood container. And not one or to that have more then 1 application in it. 
I use deluge for a long time now

**Comment by robertbaker** [comment]
I agree with that, I briefly looked at docker images for rtorrent but all
of the maintained ones have rutorrent + other stuff.

I can do a PR to add the flood only container, but we still need a rtorrent
only container

**Pull request closed without merging**
